services:

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: softy_pinko_back
    ports:
      - "5252:5252"
    restart: always

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: softy_pinko_front
    ports:
      - "9000:9000"
    restart: always